# Generated by Django 5.0.6 on 2024-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("highest", "Highest"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("lowest", "Lowest"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Task Item",
                "verbose_name_plural": "Task Items",
            },
        ),
        migrations.CreateModel(
            name="TaskItemAssignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("perm_create", models.BooleanField(default=False)),
                ("perm_read", models.BooleanField(default=True)),
                ("perm_update", models.BooleanField(default=False)),
                ("perm_delete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Task Item Assignee",
                "verbose_name_plural": "Task Item Assignees",
            },
        ),
    ]
