# Generated by Django 5.0.6 on 2024-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskitemassignee",
            name="perm_create",
            field=models.BooleanField(
                default=False, verbose_name="Has Create Permission ?"
            ),
        ),
        migrations.AlterField(
            model_name="taskitemassignee",
            name="perm_delete",
            field=models.BooleanField(
                default=False, verbose_name="Has Delete Permission ?"
            ),
        ),
        migrations.AlterField(
            model_name="taskitemassignee",
            name="perm_read",
            field=models.BooleanField(
                default=True, verbose_name="Has Read Permission ?"
            ),
        ),
        migrations.AlterField(
            model_name="taskitemassignee",
            name="perm_update",
            field=models.BooleanField(
                default=False, verbose_name="Has Update Permission ?"
            ),
        ),
    ]
