# Generated by Django 5.0.6 on 2024-06-29 08:47

import common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_taskitemassignee_perm_create_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="due_date_cannot_be_past_date",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, validators=[common.helpers.no_past_date]
            ),
        ),
    ]
